# Java 8 (Oracle) Dockerfile
# Base image: Ubuntu
# Installs: Java 8
  
FROM ubuntu:16.04

# Install basic software support
RUN apt-get update && \
    apt-get install --yes software-properties-common

# Add the JDK 8 and accept licenses (mandatory)
RUN add-apt-repository ppa:webupd8team/java && \
    echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

# Install Java 8
RUN apt-get update && \
    apt-get --yes --no-install-recommends install oracle-java8-installer
RUN apt-get update && apt-get install -y maven

# Jetty/Tomcat port
# EXPOSE 8081


RUN echo hello
